[build]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-cpu=x86-64-v3",
    "-C",
    "control-flow-guard",
    "-C",
    "link-args=/CETCOMPAT /DEBUG:NONE",
]

[profile.release]
lto = true
