name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:

  Build:
    strategy:
      matrix:
        include:
          - architecture: x86_64
            runner: windows-latest
          - architecture: aarch64
            runner: windows-11-vs2026-arm
    name: Build (${{ matrix.architecture }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo run --release
      - name: Rename binary
        run: |
          cd target\release
          ren Windows11_SupportFeed_to_HTML.exe Windows11_SupportFeed_to_HTML_${{ matrix.architecture }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.architecture }}
          path: target/release/Windows11_SupportFeed_to_HTML_${{ matrix.architecture }}.exe

  Release:
    needs: Build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            Windows11_SupportFeed_to_HTML_aarch64.exe
            Windows11_SupportFeed_to_HTML_x86_64.exe
